[package]
name = 'Integration'
version = '1.0.0'

[dependencies]
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../../aptos-core/aptos-move/framework/aptos-token" }
AptosTokenObjects = { local = "../../../aptos-core/aptos-move/framework/aptos-token-objects" }

ComponentsCommon = { local = "../components_common" }
AuctionableTokenObjects = { local = "../../auctionable_token_objects" }
TradableTokenObjects = { local = "../../tradable_token_objects" }
SellableTokenObjects = { local = "../../sellable_token_objects" }

[addresses]
integration = "0xcafe"
